[package]
name = "dryip"
description = "Short 🩸 Rust 🦀 code snippets for inspiration."
version = "0.1.6"
authors = ["azzamsa <me@azzamsa.com>"]
edition = "2021"
keywords = ["algorithms", "dryip"]
categories = ["algorithms"]
readme = "README.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/azzamsa/dryip-of-rust"

[dev-dependencies]
proptest = "1.0.0"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["user-hooks"]

[package.metadata.cargo-udeps.ignore]
development = ["cargo-husky"]
