[package]
name = "thirtyseconds"
description = "Short Rust 🦀 code snippets for inspiration."
version = "0.1.0"
authors = ["azzamsa <me@azzamsa.com>"]
edition = "2021"
keywords = ["algorithms", "30-seconds"]
categories = ["algorithms"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/azzamsa/30-seconds-of-rust"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["user-hooks"]

[package.metadata.cargo-udeps.ignore]
development = ["cargo-husky"]
