[package]
name = "thirtyseconds"
version = "0.1.0"
authors = ["azzamsa <me@azzamsa.com>"]
edition = "2021"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["user-hooks"]

[package.metadata.cargo-udeps.ignore]
development = ["cargo-husky"]
